# Python pitfalls

#### Take care that python manage negative indices : the values start then from the end of the table

In [1]:
a = [1,2,3,4,5]
print a[0]
print a[-1]
print a[-2]

1
5
4


###### Generating a double entry table : Warning, when doing :

In [2]:
def pprint(x):
  tab = str(x).split('],')
  for elem in tab:
    print elem
  print 
  return  

a=[[1,2,3,4,5]]*4

pprint(a)

a[0][0] = 9

pprint(a)

[[1, 2, 3, 4, 5
 [1, 2, 3, 4, 5
 [1, 2, 3, 4, 5
 [1, 2, 3, 4, 5]]

[[9, 2, 3, 4, 5
 [9, 2, 3, 4, 5
 [9, 2, 3, 4, 5
 [9, 2, 3, 4, 5]]



###### Better do :

In [3]:
import numpy as np

a = np.array([[1,2,3,4,5]]*4)
print "a:",a,"\n"

a[0][0] = 9

print "a:",a

a: [[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]] 

a: [[9 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]


Solution without using np : less intuitive : the loop generate different objects taking same array as value

In [4]:

a = [[1,2,3,4,5] for _ in range(4)]

pprint(a)

a[0][0] = 9

pprint(a)


[[1, 2, 3, 4, 5
 [1, 2, 3, 4, 5
 [1, 2, 3, 4, 5
 [1, 2, 3, 4, 5]]

[[9, 2, 3, 4, 5
 [1, 2, 3, 4, 5
 [1, 2, 3, 4, 5
 [1, 2, 3, 4, 5]]



## copy (references and assignement)

In [5]:
a = [1,2,3]

b = a

b[1] = 7

print 'a :', a, '\nb :', b, ', a is b:',a is b

a : [1, 7, 3] 
b : [1, 7, 3] , a is b: True


In [6]:
import copy

a = [1,2,3]

b = copy.deepcopy(a)

b[1] = 8

print 'a :', a, '\nb :', b, ', a is b:',a is b


a : [1, 2, 3] 
b : [1, 8, 3] , a is b: False


## Variables passed by reference as arrays and dictionaries modified in subroutine keep modified in main (mutable type)

In [7]:
def ff(x):
  for i in range(0,len(x)):
     ss=x[i]*x[i] 
     x[i]=ss
  print '  x in ff:',x,"\n"      
  return  
# -------------------------

xtab = [0,1,2,3]

print 'xtab:',xtab

ff(xtab)

print 'xtab after ff:',xtab



xtab: [0, 1, 2, 3]
  x in ff: [0, 1, 4, 9] 

xtab after ff: [0, 1, 4, 9]


In [8]:
def ff(x):
  for xk in x.keys():
    x[xk] += "!!"
  return

xdict = { 'a' : 'aa', 'b' : 'bb', 'c' : 'cc'}

ff(xdict)

print xdict

{'a': 'aa!!', 'c': 'cc!!', 'b': 'bb!!'}


## variable scope (global, local)

In [9]:
def f(x):
  global y
  z = 4  
  y = 2  
  return x + y

y = 3

z = 5

print 'y:',y,'z:',z

x = 3

print f(x)

print 'y:',y,'z:',z,'--> z is not modified, as y is impacted by call to f(x)'

y: 3 z: 5
5
y: 2 z: 5 --> z is not modified, as y is impacted by call to f(x)


## import collisions :

### Take care when using from import *

In [10]:
%reset -f

In [11]:
start = -1
print sum(range(5), start)

9


In [12]:
from numpy import *
print sum(range(5), start)  # using sum from numpy which works differently than native sum function

10


Better write :

In [13]:
import numpy as np 
print np.sum(range(5), start)

10


## implicit type conversion (duck typing)

In [14]:
print 4/3

1


In [15]:
a = 1
print 'type(',a,'):',type(a)
a = 1 + 4.5
print 'type(',a,'):',type(a)

type( 1 ): <type 'int'>
type( 5.5 ): <type 'float'>


## integer division (1/2=0 in py 2.x 1/2=0.5 in py3 and 1//2=0 in py3)

In [16]:
print 1/2

from __future__ import division
print (1/2)
print (1//2)

0
0.5
0


## Octal numbers start with 0 !, 010+07 = 15 (0x for hex, 0b for bin)

In [17]:
 print '10 + 7   :',10+7
 print '010 + 07 :',010+07,"In octal: {0:o}".format(010+07),"or {0:#o}".format(010+07)    
 print 'x10 + 7  :',0x10+7,"In hexadecimal: {0:x}".format(0x10+7),"or {0:#x}".format(0x10+7)   
 print '0b10 + 7 :',0b10+7,"In binary: {0:b}".format(0b10+7),"or {0:#b}".format(0b10+7) 

10 + 7   : 17
010 + 07 : 15 In octal: 17 or 0o17
x10 + 7  : 23 In hexadecimal: 17 or 0x17
0b10 + 7 : 9 In binary: 1001 or 0b1001


As a consequence:

In [18]:
print 09

SyntaxError: invalid token (<ipython-input-18-ede1f0e17502>, line 1)

But numbers with component less than 8 are valid :

In [19]:
print 01,07

1 7


## runtime errors are not caught until function executes

In [20]:
a = 5
if a == 4:
  c = a + b
 
if a == 5:
  c = a + b
    

NameError: name 'b' is not defined

In [21]:
def divisionError():
  if a==5:
    c = a / 0
  return

if a==4:
  print "First call:"
  divisionError() 
    
if a==5:
  print "Second call:"
  divisionError()  

Second call:


ZeroDivisionError: division by zero