# An Introduction to numerical computing with Python

Python is an excellent tool for general-purpose programming with rich and powerful data types :
* strings,
* lists,
* sets,
* dictionaries,
* ...

It is however poorly suited for :
* efficient representation of multidimensional datasets,
* efficient mathematical and scientific computing,
* data visualization.

In particular, Python lists are very flexible containers that can be nested arbitrarily deep and which can hold any Python object in them, but they are poorly suited to represent efficiently common mathematical constructs like vectors and matrices.

**Basic needs** :

* Fortran-like efficient mathematical functions that can efficiently operate on entire arrays at once,
* Powerful data structure : multi-dimensional arrays,
* Friendly syntax for data selection/manipulation/visualisation.

Two major libraries answer these particular needs :
* **Numpy**,
* **Pandas**

## Panda : Python tools for data analysis ##

### Key points ###

* emphasis on tabular data (csv, Excel, HDF5, etc.)
* database/spreadsheet-like functionalities
* rich support for mixed data (numpy is for **homogeneous** arrays of fixed size-items)
* integrates cleanly with numpy and matplotlib

### References ###
+ Nice [free Pandas tutorials](https://bitbucket.org/hrojas/learn-pandas)
+ Official ["10 Minutes to Pandas"](http://pandas.pydata.org/pandas-docs/stable/10min.html) guide

## Numpy basics ##

Heavily used in <a href="http://www.astroml.org/index.html" target="_blank">
<img src="./files/images/astroml.gif"></a> (Python module for statistics, data mining, and machine learning in Astronomy)

You can import [Numpy](http://docs.scipy.org/doc/numpy/) like this :

In [1]:
import numpy as N

Numpy provides the multi-dimensional array class [ndarray](http://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.html "Numpy ndarray documentation") :

<center>
<img src="./files/images/dtype.png" width=60%>
</center>

### The _dtype_ attribute ###
A *ndarray* object has a **dtype** attribute that describes the type of every item contained in the array structure :

In [2]:
a = N.array([1.3, 5.2, 3.14])
print a
print "ndarray object type : ", type(a)
print "array item type : ", a.dtype

[ 1.3   5.2   3.14]
ndarray object type :  <type 'numpy.ndarray'>
array item type :  float64


The data type is set once and for all upon array creation.

__Warning__ : if you want to set a float value into an integer array, the value will be automatically converted into an integer !

In [3]:
i = N.array([14, 2, 98], dtype=int)
print i

[14  2 98]


In [4]:
i[1] = 78.836
print i

[14 78 98]


### The _ndim_, _shape_ and _size_ attributes ###

Among many others, a _ndarray_ object has three other frequently used attributes :
* [ndim](http://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.ndim.html#numpy.ndarray.ndim) : the dimension number
* [shape](http://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.shape.html#numpy.ndarray.shape) : the size of the array along each dimension
* [size](http://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.size.html#numpy.ndarray.size) : the total number of elements of the _ndarray_

In [5]:
a = N.array([[1,2,3,4,5],[21,22,23,24,25]], dtype=int)
print a
print "Dims : ", a.ndim
print "Shape : ", a.shape
print "number of elements : ", a.size

[[ 1  2  3  4  5]
 [21 22 23 24 25]]
Dims :  2
Shape :  (2, 5)
number of elements :  10


## What is the difference between a list and a ndarray ? ##

ndarray objects are __homogeneous__, all elements of a ndarray must be of the same type.
In contrast, lists can contain elements of arbitrary type. For example :

In [6]:
l = [1, 56, 47, 4.125, "Hello world !"] # Heterogeneous items in a list !
l

[1, 56, 47, 4.125, 'Hello world !']

### Element indexing ###

Elements of a one-dimensional ndarray are accessed with the same syntax as a list:

In [7]:
iarray = N.array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29], dtype=int)
iarray[0] # first element

20

In [8]:
iarray[-1] # Last element

29

In [9]:
iarray[2:9:2] # Every other element from index 2 to 8.

array([22, 24, 26, 28])

In [10]:
iarray[::-1] # Reversed array

array([29, 28, 27, 26, 25, 24, 23, 22, 21, 20])

In [11]:
iarray2 = N.array([[10,11],[20,21],[30,31],[40,41]]) # 2D array
print iarray2

[[10 11]
 [20 21]
 [30 31]
 [40 41]]


#### Masking : array indexing with another array ####

You can filter an array using another _boolean_ array as a mask :

In [12]:
r = N.array([-1.2, 0.5, 5.8, -4.5, 9.1, 12.7, 0.0, -4.25])
mask = (r<0.0)
print mask
print r[mask] # Negative values
print r[~mask] # Positive or null values ('~' is the 'not' unary operator)

[ True False False  True False False False  True]
[-1.2  -4.5  -4.25]
[  0.5   5.8   9.1  12.7   0. ]


In [13]:
r[(r>-2.0)&(r<2.0)] # Inline mask with boolean operation

array([-1.2,  0.5,  0. ])

Useful masking functions : [isnan](http://docs.scipy.org/doc/numpy/reference/generated/numpy.isnan.html), [isinf](http://docs.scipy.org/doc/numpy/reference/generated/numpy.isinf.html), [isposinf](http://docs.scipy.org/doc/numpy/reference/generated/numpy.isposinf.html), [isneginf](http://docs.scipy.org/doc/numpy/reference/generated/numpy.isneginf.html).

##### Fancy indexing : indexing with tuples #####

You can use tuples of indices, as returned by the [where(condition)](http://docs.scipy.org/doc/numpy/reference/generated/numpy.where.html) function to filter an array (similar to IDL) :

In [14]:
r2 = r.reshape((4,2))
print r2
i_ind, j_ind = N.where((r2<0.0))
print "total number : ", i_ind.size
print "(i,j) indexes list : ", zip(i_ind, j_ind)
print "negative values : ", r2[i_ind, j_ind]

[[ -1.2    0.5 ]
 [  5.8   -4.5 ]
 [  9.1   12.7 ]
 [  0.    -4.25]]
total number :  3
(i,j) indexes list :  [(0, 0), (1, 1), (3, 1)]
negative values :  [-1.2  -4.5  -4.25]


In [15]:
N.where(r2 > 1.0, r2, 0.5) # returns r2[i,j] if condition is true, otherwise returns 0.5

array([[  0.5,   0.5],
       [  5.8,   0.5],
       [  9.1,  12.7],
       [  0.5,   0.5]])

##### Reordering #####

Reordering an array can be done using the [argsort(array)](http://docs.scipy.org/doc/numpy/reference/generated/numpy.argsort.html) function :

In [16]:
X = N.array([0.5, 3.5, -21.2, -2.6, 0.9, 4.8, 6.55, 0.1, -5.8])
ind = N.argsort(X) # Indices of X that, when applied on X, reorder X in ascending order.
print X.shape, ind.shape
print ind

(9,) (9,)
[2 8 3 7 0 4 1 5 6]


In [17]:
print X[ind] # Reordered X array

[-21.2   -5.8   -2.6    0.1    0.5    0.9    3.5    4.8    6.55]


See also : [argmin](http://docs.scipy.org/doc/numpy/reference/generated/numpy.argmin.html), [argmax](http://docs.scipy.org/doc/numpy/reference/generated/numpy.argmax.html), [searchsorted](http://docs.scipy.org/doc/numpy/reference/generated/numpy.searchsorted.html), [sort](http://docs.scipy.org/doc/numpy/reference/generated/numpy.sort.html)

### Slicing ###

X[first:last:step] returns :

- a *copy* of X if X is a **list**,
- a *reference* over X if X is a **ndarray** object (a view, not a copy => no memory duplication).

In [18]:
iarray2 = N.array([[10,11],[20,21],[30,31],[40,41]]) # 2D array
iarray2[1,:] # Second row reference

array([20, 21])

In [19]:
iarray2[:,1]=-1 # Set second colum elements to -1
print iarray2

[[10 -1]
 [20 -1]
 [30 -1]
 [40 -1]]


**See also** :
- [Official Numpy indexing and slicing guide](http://docs.scipy.org/doc/numpy/reference/arrays.indexing.html)

## Reshaping ndarray objects ##

Note that, as long as the number of items remains unchanged, the shape of the array can be modified (without memory duplication) using the [reshape](http://docs.scipy.org/doc/numpy/reference/generated/numpy.reshape.html) function. The reshaping process only provides a different view of the same data:

In [20]:
A = N.arange(10)
print A
print "Reshaping..."
Ar = A.reshape((2,5))
A[3] = 100 # Modification of A => Ar is also modified
print Ar

[0 1 2 3 4 5 6 7 8 9]
Reshaping...
[[  0   1   2 100   4]
 [  5   6   7   8   9]]


## Ufuncs ##

In Numpy, a **ufunc** is a *Universal Function*. This is a very efficient _compiled_ (compiled in C) function which operates **element-wise** on an array. 

### Avoid loops at all cost !!! ###

Let's try to substract 2 (1000,1000) arrays :

In [21]:
def substract(a,b):
    return a - b

def substract_loop(a,b):
    x = N.empty(a.shape)
    for i in range(a.shape[0]):
        for j in range(a.shape[1]):
            x[i,j] = a[i,j] - b[i,j]
    return x

In [22]:
a = N.random.random((1000,1000))

b = N.random.random((1000,1000))

In [23]:
timeit substract(a,b)

100 loops, best of 3: 2.22 ms per loop


In [24]:
timeit substract_loop(a,b)

1 loops, best of 3: 465 ms per loop


Ufunc 100+ times faster than loops !

### Arithmetic operations ###

In [25]:
x = N.arange(5, dtype=float)
print "x :", x
y = N.arange(10,60,10, dtype=float)
print "y: ", y
print x+y

x : [ 0.  1.  2.  3.  4.]
y:  [ 10.  20.  30.  40.  50.]
[ 10.  21.  32.  43.  54.]


In [26]:
y-x

array([ 10.,  19.,  28.,  37.,  46.])

In [27]:
x**2

array([  0.,   1.,   4.,   9.,  16.])

In [28]:
x/y

array([ 0.        ,  0.05      ,  0.06666667,  0.075     ,  0.08      ])

### In-place array operations ###

In [29]:
y -= 3.0
print y

[  7.  17.  27.  37.  47.]


In [30]:
y *= 2
print y

[ 14.  34.  54.  74.  94.]


### Math functions ###

In [31]:
N.sin(x)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [32]:
N.exp(x)

array([  1.        ,   2.71828183,   7.3890561 ,  20.08553692,  54.59815003])

In [33]:
N.sqrt(x)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ])

### User defined ufunc ###

See the detailed instructions on [how to write a user-defined ufunc](http://scipy-lectures.github.io/advanced/advanced_numpy/#universal-functions).

## Creating arrays ##

### Constant values ###

The [ones(shape, dtype)](http://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html) and [zeros(shape, dtype)](http://docs.scipy.org/doc/numpy/reference/generated/numpy.zeros.html) methods return array objects of the requested shape and type (filled with 0 or 1) :

In [34]:
b = N.ones((5,3), dtype=float)
print b

[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]


In [35]:
c = N.zeros((3,2), dtype=complex)
print c

[[ 0.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j]
 [ 0.+0.j  0.+0.j]]


### Linearly (and log-) spaced values ###
[arange(first, last, step, type)](http://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html) works like the built-in range methods (but returns a ndarray object instead of a list).

In [36]:
x = N.arange(-2, 11, 1, int)   # upper limit 11 is not included!!
print x

[-2 -1  0  1  2  3  4  5  6  7  8  9 10]


the [linspace(a, b, n)](http://docs.scipy.org/doc/numpy/reference/generated/numpy.linspace.html) and the [logspace(log10_a, log10_b, n)](http://docs.scipy.org/doc/numpy/reference/generated/numpy.logspace.html) methods can create linearly and logarithmically-spaced grids respectively, with a fixed number of points and including both ends of the specified interval $[a,b]$ :

In [37]:
x = N.linspace(0., 10., 5)
print x

[  0.    2.5   5.    7.5  10. ]


In [38]:
y = N.logspace(1,4,4) # from 10¹ to 10⁴ log range
print y

[    10.    100.   1000.  10000.]


### Random valued arrays ###

To create arrays with values following a specific distribution, you can use the [random](http://docs.scipy.org/doc/numpy/reference/random.html) module of Numpy. The [random.randn(n)](http://docs.scipy.org/doc/numpy/reference/generated/numpy.random.randn.html) method can be used to create an array of 10 random values from a standard normal distribution ($\rho=0$ and $\sigma=1$):

In [39]:
N.random.randn(10)

array([-1.58708236,  1.83152837,  0.75510152, -0.68381827, -0.03567136,
       -2.08352397, -0.86256652, -0.76857158,  2.21449902, -1.09340676])

For user-defined mean value $\rho$ and standard deviation $\sigma^{2}$ normal distribution, use the [random.normal(rho, var, n)](http://docs.scipy.org/doc/numpy/reference/generated/numpy.random.normal.html) method :

In [40]:
N.random.normal(15.0, 3.5, 10) # 10 values, normal distribution with mean=15 and variance=3.5

array([ 19.37298585,  16.31464323,  20.27194299,  21.18321444,
         9.78893662,  12.61872723,  13.25592629,  14.63297006,
        15.95781457,  14.70753494])

For uniform distribution, use [random.uniform(low, high, size)](http://docs.scipy.org/doc/numpy/reference/generated/numpy.random.uniform.html) :

In [41]:
N.random.uniform(-1.0, 1.0, (2,3)) # (2,3) shaped array of uniformly distributed values in [-1.0, 1.0]

array([[-0.58613831,  0.54758298,  0.18350712],
       [-0.31154128,  0.11797505, -0.82412022]])

### From a user-defined Python function ###

Use the [fromfunction(func, shape)](http://docs.scipy.org/doc/numpy/reference/generated/numpy.fromfunction.html) method :

In [42]:
def custom_func(i, j):
    return (j-i+1)*(j**3+i**2)

# make 5x3 array where a[i,j] = custom_func(i,j):
N.fromfunction(custom_func, (5,3))

array([[  0.,   2.,  24.],
       [  0.,   2.,  18.],
       [ -4.,   0.,  12.],
       [-18., -10.,   0.],
       [-48., -34., -24.]])

### Import from ASCII file ###

Numpy provides a very handy [genfromtxt(fname)](http://docs.scipy.org/doc/numpy/reference/generated/numpy.genfromtxt.html) method to import data from an ASCII file and create the corresponding _ndarray_ object(s).

In [43]:
a, e, i, H, diameter, BV, UB = N.genfromtxt("data/asteroids_data.csv", delimiter=',', unpack=True)
print a.shape
print "Missing diameter data : ", N.isnan(diameter).sum()

(5000,)
Missing diameter data :  3082


**See also** :

- the [loadtxt(fname)](http://docs.scipy.org/doc/numpy/reference/generated/numpy.loadtxt.html) method (do not handle missing data like _genfromtxt_),
- [Importing data with genfromtxt](http://docs.scipy.org/doc/numpy/user/basics.io.genfromtxt.html) guide.


### Import from other formats ###

See :
- [Numpy I/O routines](http://docs.scipy.org/doc/numpy-1.9.1/reference/routines.io.html),
- [Scipy I/O module](http://docs.scipy.org/doc/scipy-0.15.1/reference/tutorial/io.html) (Matlab, IDL, NetCDF, ...),
- HDF5 format : [PyTables](https://pytables.github.io/usersguide/tutorials.html) and [h5py](http://docs.h5py.org/en/latest/quick.html).

## Broadcasting ##

Broadcasting is one of the most powerful process for both cpu and memory efficiency in Numpy. When performing operations between two _ndarray_ objects :

1. If the two arrays differ in their number of dimensions, the shape of the array with fewer dimensions is *padded* with ones on its leading (left) side.

2. If the shape of the two arrays does not match in any dimension, the array with shape equal to 1 in that dimension is *stretched* to match the other shape.

3. If in any dimension the sizes disagree and neither is equal to 1, an error is raised.

**Note** : all of this happens without ever actually creating the stretched arrays in memory or replicating the data. In the example below the operations are carried out without allocating memory for the dotted cells.

In [44]:
N.arange(5) + 10

array([10, 11, 12, 13, 14])

<center>
    <img src="./files/images/broadcast_fig_1.png" width=80%>
</center>

Here, the scalar 10 is:

* first 'promoted' to a 1-dimensional array of length 1,
* then, this array is 'stretched' to length 5 to match the first array.

After these two operations are complete, the addition can proceed as now both operands are one-dimensional arrays of length 5.

In [45]:
N.ones((3,5)) + N.arange(10,15)

array([[ 11.,  12.,  13.,  14.,  15.],
       [ 11.,  12.,  13.,  14.,  15.],
       [ 11.,  12.,  13.,  14.,  15.]])

<center>
    <img src="./files/images/broadcast_fig_2.png" width=80%>
</center>

Here, the second array is:

- first 'promoted' to a 2-dimensional array of shape (1, 5),
- then 'stretched' to length 3 to match the first array.

Then the operation proceeds as if on two 3 $\times$ 5 arrays.

In [46]:
N.arange(10,40,10).reshape((3,1)) + N.arange(5)

array([[10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34]])

<center>
    <img src="./files/images/broadcast_fig_3.png" width=80%>
</center>

Here:
- the second array is 'promoted' to a 2-dimensional array of shape (1, 5),
- the second array is 'stretched' to shape (3, 5),
- the first array is 'stretched' to shape (3, 5).

Then the operation proceeds as if on two 3 $\times$ 5 arrays.

### The newaxis parameter ###

To define wxplicitly which dimension you would like to extend, use the [numppy.newaxis](http://docs.scipy.org/doc/numpy/reference/arrays.indexing.html#numpy.newaxis) parameter :

In [47]:
X = N.arange(10, 31, 10)
Y = N.arange(5)
X[:, N.newaxis] + Y # X is turned into a column-like vector !

array([[10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34]])

## Aggregates ##

Aggregates are Numpy functions that operates over an array and returns an array of smaller shape.

In [48]:
ran = N.random.uniform(0, 3, (5, 3))
print ran

[[ 0.41467649  1.76242803  0.42338745]
 [ 1.66285676  0.11808132  1.7579443 ]
 [ 1.18221391  2.09133406  1.05487041]
 [ 1.42435698  1.19151915  2.74139449]
 [ 0.35179189  1.61095773  2.44189357]]


In [49]:
ran.sum() # Sum of all array elements (Same as 'N.sum(ran)')

20.229706519837894

In [50]:
ran.mean() # Mean value of all array elements

1.3486471013225263

In [51]:
ran.std() # Standard deviation

0.75602625126439726

In [52]:
ran.prod() # Product of all array ellements

1.7935216018689242

#### Aggregates over a particular axis ####

In [53]:
N.max(ran, axis=0) # Max value over rows (1 value per column)

array([ 1.66285676,  2.09133406,  2.74139449])

## Linear algebra ##

You can use the [numpy.matrix()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.matrix.html#numpy.matrix) function to create a _matrix_ object (inherits from _ndarray_ class) :

In [54]:
A = N.matrix([[1.0, 2.0], [3.0, 4.0]])
print A, type(A)
print "Transpose : ", A.T  # transpose

[[ 1.  2.]
 [ 3.  4.]] <class 'numpy.matrixlib.defmatrix.matrix'>
Transpose :  [[ 1.  3.]
 [ 2.  4.]]


In [55]:
Y = N.matrix([[5.0], [7.0]])
print Y
print "A*Y = ", A*Y  # matrix multiplication

[[ 5.]
 [ 7.]]
A*Y =  [[ 19.]
 [ 43.]]


In [56]:
print A.I  # inverse

[[-2.   1. ]
 [ 1.5 -0.5]]


In [57]:
X = N.linalg.solve(A, Y)  # solving linear equation A*X = Y
print X

[[-3.]
 [ 4.]]


For more functionalities, see the [numpy.linalg](http://docs.scipy.org/doc/numpy/reference/routines.linalg.html) module... Or wait for the "Scientific python" session (session #8, tomorrow !).

## Computation/memory efficiency quicksheet for Numpy ##

When operating on _ndarray_ objects :

1. Use Numpy **ufuncs** every time you can,
2. Use Numpy **aggregates** to you advantage,
3. Use Numpy **broadcasting** syntax as much as you can,
4. Use Numpy **slicing and masking** to view/filter subparts of a _ndarray_,
5. Do not be affraid of interfacing (already implemented, maybe your own ?) **compiled code** (C, Fortran, cython, SWIG, etc.) with your Python code.

## Numpy references ##

<UL>
<LI> <A HREF="http://wiki.scipy.org/Tentative_NumPy_Tutorial">Tentative Numpy Tutorial</A>
<LI> <A HREF="http://docs.scipy.org/doc/numpy/reference">NumPy Reference</A>
<LI> <A HREF="http://mathesaurus.sourceforge.net/matlab-numpy.html">NumPy for MATLAB Users</A>
</UL>

# Breakout session #

## Part 1 : Asteroid data manipulation ##

- Load the 'data/asteroids\_data.csv' file using genfromtxt  into a **data** _ndarray_ object (This is a .csv file, so the delimiter is ',').
- How many asteroids are there in this catalog ? How many variables (columns) ?

In [58]:
#data = N.genfromtxt(...)

- the file header describes the various columns as " # a, e, i, H, diameter, BV, UB". Using slicing syntax, create the corresponding views **a**, **e**, **i**, **H**, **diameter**, **BV**, **UB** for each column of the **data** _ndarray_.

In [59]:
#a = data[...]
#e = ...

- Compute the asteroids semi-minor axis $b=a\sqrt{1-e^{2}}$ and _mean radius_ $r_{\tt mean}=\sqrt{a b}$.

In [60]:
# b = ...
# r_mean = ...

- This catalog contains missing data. Using _isnan()_ and _sum()_ numpy functions over the **data** _ndarray_, determine how many values are missing for each field (column).
- Using the _not_ unary operator (~) and the _any()_ and _isnan()_ functions , compute a (row) mask **msk** of the asteroids that do not contain any missing data. How many (valid) asteroids are in this case ?

In [61]:
# nmiss = ...
# msk = ...

- Set the valid asteroids masked views of the mean radius $r_{\tt mean}$ into **r_mean2** and of the BV luminosity into **BV2**. Using the _argsort()_ function, reorder the **BV2** _ndarray_ into ascending mean radius order and display the 10 last values of the reordered array.

In [62]:
# r_mean2 = ...
# BV2 = ...
# ind_r = N.argsort(...)

- In a single command, compute the mean values of each field, for the valid asteroids only.

In [63]:
# Use N.mean() function with the 'axis' parameter

## Part 2 : Plotting ##

- Convert i (in degrees) in radians using ``numpy.pi`` parameter and plot the semi-minor axis _a_ versus the sine of the inclination angle into a [scatter](http://matplotlib.org/api/pyplot_api.html?highlight=scatter#matplotlib.pyplot.scatter) plot using [Matplotlib](http://matplotlib.org/index.html) (stay with us ! More about plotting in next session...) :

In [64]:
# i_rad = ...

# Inline Matplotlib figures into the notebok (ipython magic) !
% matplotlib inline

import matplotlib.pyplot as P
# P.scatter(x, y)
#P.xlabel("sin(i)")
#P.ylabel("semi-minor axis")

- Draw a color-magnitude scatter plot of the 'valid' asteroids (H vs B-V).  Can you identify two distinct "families" of asteroids in this plot ?.  Over-plot a line that divides these.

In [65]:
# P.scatter(x, y)
# P.plot(x, y, color='r') # To draw a line given x and y coords
# P.xlabel("H")
# P.ylabel("B-V")
# P.xlim(xmin, xmax) # Set min/max x-axis limits

- Repeat the orbital parameter plot from above, but plot the two "families" in different colors. Note that this magnitude is undefined for many of the asteroids.  Do you see any correlation between color and orbit?

In [66]:
# no_magn = ~msk
# fam1_msk = ...
# fam2_msk = ...
# P.scatter(x0, y0, color='blue')
# P.scatter(x1, y1, color='red')
# P.scatter(x2, y2, color='green')
# P.xlabel("sin(i)")
# P.ylabel("semi-minor axis")